/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houserentalmanagementsystem;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author Acer
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }
    
         public void close()
    {
        WindowEvent windowevent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowevent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        profile = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        addTenants = new javax.swing.JButton();
        tenantsList = new javax.swing.JButton();
        addApartment = new javax.swing.JButton();
        apartmentInformation = new javax.swing.JButton();
        tenantsPay = new javax.swing.JButton();
        mainfee = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        signOut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel1.setText("Dashboard");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 200, 50));

        profile.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        profile.setText("DUE PAY");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jPanel1.add(profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 320, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jButton1.setText("FEE LIST");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 320, 40));

        addTenants.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        addTenants.setText("Add Tenants");
        addTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTenantsActionPerformed(evt);
            }
        });
        jPanel1.add(addTenants, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 320, 40));

        tenantsList.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        tenantsList.setText("Tenants List");
        tenantsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantsListActionPerformed(evt);
            }
        });
        jPanel1.add(tenantsList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 320, 40));

        addApartment.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        addApartment.setText("Add Apartment");
        addApartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addApartmentActionPerformed(evt);
            }
        });
        jPanel1.add(addApartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 320, 40));

        apartmentInformation.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        apartmentInformation.setText("Apartment Information");
        apartmentInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apartmentInformationActionPerformed(evt);
            }
        });
        jPanel1.add(apartmentInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 320, 40));

        tenantsPay.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        tenantsPay.setText("Tenants Pay");
        tenantsPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenantsPayActionPerformed(evt);
            }
        });
        jPanel1.add(tenantsPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 320, 40));

        mainfee.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        mainfee.setText("Maintainance Fee");
        mainfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainfeeActionPerformed(evt);
            }
        });
        jPanel1.add(mainfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 320, 40));

        jButton2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jButton2.setText("Pay List");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 320, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        signOut.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        signOut.setText("Sign Out");
        signOut.setToolTipText("");
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(701, Short.MAX_VALUE)
                .addComponent(signOut)
                .addGap(206, 206, 206))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(signOut)
                .addGap(33, 33, 33))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon("F:\\House Rental Management System\\home.png")); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setText("HOUSE RENTAL MANAGEMENT SYSTEM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
           duepay due =new duepay();
           due.setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void addApartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addApartmentActionPerformed
       AddApartment addapartment = new AddApartment();
       addapartment.setVisible(true);
    }//GEN-LAST:event_addApartmentActionPerformed

    private void tenantsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantsListActionPerformed
      TenantsList tenantlist = new TenantsList();
      tenantlist.setVisible(true);
    }//GEN-LAST:event_tenantsListActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           feesList fees = new feesList();
           fees.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTenantsActionPerformed
        AddTenants addtenants = new AddTenants();
        addtenants.setVisible(true);
    }//GEN-LAST:event_addTenantsActionPerformed

    private void apartmentInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apartmentInformationActionPerformed
         ApartmentList apartment = new ApartmentList();
         apartment.setVisible(true);
    }//GEN-LAST:event_apartmentInformationActionPerformed

    private void mainfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainfeeActionPerformed
       Maintainance_fee mainfee = new  Maintainance_fee();
       mainfee.setVisible(true);
    }//GEN-LAST:event_mainfeeActionPerformed

    private void tenantsPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenantsPayActionPerformed
        tenantsPay tenantpay = new tenantsPay();
        tenantpay.setVisible(true);
    }//GEN-LAST:event_tenantsPayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      paylist pay = new paylist();
      pay.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        frontpage fp = new frontpage();
        fp.setVisible(true);
    }//GEN-LAST:event_signOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addApartment;
    private javax.swing.JButton addTenants;
    private javax.swing.JButton apartmentInformation;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mainfee;
    private javax.swing.JButton profile;
    private javax.swing.JButton signOut;
    private javax.swing.JButton tenantsList;
    private javax.swing.JButton tenantsPay;
    // End of variables declaration//GEN-END:variables
}
